### ISSUE TITLE
Errores en uso de la definición SERVIDOR

### ISSUE THREAD

**Issue by ehooo** [CriptoPay/CriptoPay_API_PHP#1]
Se usa SERVIDOR en: https://github.com/CriptoPay/CriptoPay_API_PHP/blob/master/src/CriptoPay_Cliente_API_Cifrado.php#L65 mientras que en: https://github.com/CriptoPay/CriptoPay_API_PHP/blob/master/src/CriptoPay_Cliente_API.php#L59 el servidor esta hardcodeado.

Además debería de hacer se un "define" o un "defined" antes de usar esa definición para eviar errores en ejecución:

```
if(!defined("SERVIDOR")){
  define("SERVIDOR", "http://api.cripto-pay.com/")
  if(defined("CIFRADO") && CIFRADO)
    define("SERVIDOR", "https://api.cripto-pay.com/")
}
```

**Comment by vgpastor** [comment]
Se ha actualizado el repositorio, en CriptoPay_Cliente_API.php está escrito a "mano" puesto que es un servidor en desuso y solo se admite a través de ese enlace.

**Comment by ehooo** [comment]
Entonces como se conecta con sandbox.cripto-pay.com?

**Comment by vgpastor** [comment]
Se ha actualizado la clase para que al entrar en modo debug se conecte automáticamente con el servidor sandobox
